### ISSUE TITLE
minimum-change-threshold not taking effect

### ISSUE THREAD

**Issue by pauldambra** [preactjs/compressed-size-action#102]
Hey,

We have this config

```
            - name: Check toolbar bundle size
              if: needs.changes.outputs.frontend == 'true'
              uses: preactjs/compressed-size-action@v2
              with:
                  build-script: 'build'
                  compression: 'none'
                  pattern: 'frontend/dist/toolbar.js'
                  minimum-change-threshold: 100
```

The action runs correctly. But we added the `minimum-change-threshold: 100` and it isn't taking effect.

You can see here that we're getting the comment despite 0B change https://github.com/PostHog/posthog/pull/19014#issuecomment-1835980534

Am I doing something silly?
