### ISSUE TITLE
Usage with Next.js?

### ISSUE THREAD

**Issue by danawoodman** [preactjs/compressed-size-action#25]
`next build` generates a variety of file formats and using a single regex seems near impossible to match things properly. Here are some of the static build files Next.js creates:

```
.next/static/EWRdXUQq4dZmLtDf6_2AJ/pages/home.js
.next/static/chunks/018f516e3e474ffd4b3ae00965a7b7def9dd6244.aff82a9664f27ba4ff5a.js
.next/static/runtime/main-98aa32f16d7d5354970b.js
.next/static/runtime/polyfills-895c6aa13952c0a67e69.js
```

Any suggestions/ideas how to use the `strip-hash` regex or something else to get a normalized list of changed files?

Related question: is there a way to customize the output display of the action? Would be nice to have all assets collapsed by default including changed files.

**Comment by developit** [comment]
Just a note - collapsing only works on the GitHub web version.

**Comment by danawoodman** [comment]
> Just a note - collapsing only works on the GitHub web version.

Good to know. I am talking about web though, BTW 👍

**Comment by developit** [comment]
For Next.js, I believe the following pattern should work.

Also note the `use-check` option: we just added this in `v2` and I think it might be what you're looking for regarding avoiding the comments. It uses a standard GitHub Status Check (similar to a CI run) that links to a full-page size table, instead of commenting the sizes on the PR.

```yaml
name: Compressed Size
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "./.next/static/**/*.js"
        strip-hash: "(?:runtime/\\w+-(\\w{20}).js$|chunks/\\w{40}\\.(\\w{20})\\.js$|static/(\\w{20,21})/)"
        use-check: true
```

**Comment by alex-grover** [comment]
it looks like Next has changed a bit since this thread was closed. I'm getting it working now (Next 12.1.4 and 12.2.5) with the following:

```
pattern: ".next/static/chunks/**/*.js"
strip-hash: "\\w+-(\\w{16}).js$"
```

**Comment by ismay** [comment]
I'm using this action with next.js 13. The configuration is pretty similar to @alex-grover's config, but I've added a couple of patterns:

```
name: size

on: [pull_request]

jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: "{./.next/static/chunks/**/*.js,.next/static/css/*.css,.next/server/pages/*.{html,json}}"
          exclude: "{**/*.map,**/*.nft.json,**/node_modules/**}"
          strip-hash: "\\w+-(\\w{16}).js$"
```

- `./.next/static/chunks/**/*.js`: client side app bundles
- `.next/static/css/*.css`: css
- `.next/server/pages/*.{html,json}`: static html and potentially any json for pages that use getStaticProps

The files matching `.next/static/{hash}/_{buildManifest,ssgManifest}.js` are sent to clients as well, but since they're not directly under your control I thought it was fine to leave them out.
