### ISSUE TITLE
total size 0B?

### ISSUE THREAD

**Issue by FezVrasta** [preactjs/compressed-size-action#3]
Hi, I'm trying to integrate this in my repo, but the report reports 0 bytes.

Do I have to specify the dist files somehow?

Test PR here:
https://github.com/popperjs/popper-core/pull/975

**Comment by FezVrasta** [comment]
Ok, nevermind, I needed to specify the `pattern` parameter:

```
name: Compressed Size

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - uses: preactjs/compressed-size-action@v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: 'dist/umd/*.js'

```
