### ISSUE TITLE
Directory support for monorepo

### ISSUE THREAD

**Issue by azu** [preactjs/compressed-size-action#38]
Unfortunately, GitHub Actions does nose support the combination of `working-directory`  and `uses` & `with`.
So, we can not use this action for subdirectory package like monorepo .

```yaml
name: builder size
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v1
      - name: size check
        uses: preactjs/compressed-size-action@v2
        working-directory: ./packages/foo # This is invalid syntax
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          pattern: './build-output/**/*.js'
          build-script: 'build'
```

- [Unable to use working-directory with docker based actions - GitHub Actions - GitHub Support Community](https://github.community/t/unable-to-use-working-directory-with-docker-based-actions/16419/3)

Probably, `directory` option or `shell-script` option will resolve this issue.

Currently, `build-script` specify npm run-script.
If this action provide `shell-script`, it allow us to write `shell-script: cd packages/foo && npm run build`.
