### ISSUE TITLE
Error: digital envelope routines::unsupported

### ISSUE THREAD

**Issue by selankon** [preactjs/compressed-size-action#91]
Using this action I am getting the following error when running the `preactjs/compressed-size-action@v2` step:

```
  Error: error:0308010C:digital envelope routines::unsupported
```

On my computer it builds everything propeperly with node `v16.18.0`. 

On this job it failed.

https://github.com/libremesh/lime-app/actions/runs/4740204197/jobs/8415775391?pr=380

Any idea?

**Comment by rschristian** [comment]
That's a Webpack v4 on Node 16+ issue, unrelated to this action.

See https://github.com/preactjs/preact-cli/issues/1773#issuecomment-1380467094

**Comment by selankon** [comment]
Adding this action worked:

```yaml
      - name: Install node
        uses: actions/setup-node@v3
        with:
            node-version: 16
```

Rather than specifying node version on checkout action. This didn't work:

```yaml
      - uses: actions/checkout@v3
        with:
            node-version: '16'
```
