### ISSUE TITLE
Allow setting environment variables before install

### ISSUE THREAD

**Issue by swissspidy** [preactjs/compressed-size-action#94]
Would be nice if it's somehow possible to set `PUPPETEER_SKIP_DOWNLOAD=true` before the action runs `npm ci`.

**Comment by PixnBits** [comment]
FWIW you might be able to do so via [`jobs.<job_id>.steps[*].env`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv), i.e.:
```yaml
...
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        env:
          PUPPETEER_SKIP_DOWNLOAD: true
```
