### ISSUE TITLE
 ERROR  Headless installation requires a pnpm-lock.yaml file

### ISSUE THREAD

**Issue by lixiaofa** [preactjs/compressed-size-action#98]
```
   - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: './dist/fast-plus/dist/*.{js,mjs,css}'
        env:
          NODE_OPTIONS: --max-old-space-size=4096

```
Error reporting：
![image](https://github.com/preactjs/compressed-size-action/assets/23230215/b4c4dd69-f3c9-4ade-a629-8d00916e99aa)
I don't have any installed commands
